### ISSUE TITLE
Python Script Broken

### ISSUE THREAD

**Issue by Betaforgez** [elfnor/mesh_maze#12]
[mesh_maze-master.zip](https://github.com/elfnor/mesh_maze/files/8376019/mesh_maze-master.zip)
Same exact file, when opened and used it gives and error message and when I proceed to console I get a dialect of other Python coding, I think the coding you have is outdated.

**Comment by elfnor** [comment]
What version of Blender are you using? It works for me on Blender  3.1.2 and 2.9.0 and I presume those in between.

**Comment by havocfire** [comment]
Could you update it for Blender 4.1 and 4.2?

> Traceback (most recent call last):
  File "~blender-4.2.0-alpha+main.c2b56ca4688e-windows.amd64-release\4.2\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~blender-4.2.0-alpha+main.c2b56ca4688e-windows.amd64-release\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesh_maze-3'

**Comment by elfnor** [comment]
I'll have a look

**Comment by haskins-io** [comment]
Seeing the same problem with Blender 4.0.2 2023-12-05

**Comment by elfnor** [comment]
I've tried it on Blender 4.0.2 and 4.1.0 (on Linux) and I'm seeing no errors.
Any more details?
