### ISSUE TITLE
Blender 2.83

### ISSUE THREAD

**Issue by BlenderPete** [elfnor/mesh_maze#3]
Using the addon in Blender 2.83 gives the following error:
Traceback (most recent call last):
  File "C:\Blender\2.83\2.83\scripts\addons\mesh_maze-master\__init__.py", line 225, in execute
    bm, self.link_centers, self.vert_centers = mesh_maze.generate_maze(bm, maze_params)
  File "C:\Blender\2.83\2.83\scripts\addons\mesh_maze-master\mesh_maze.py", line 54, in generate_maze
    bevel_extrude(bm, sel_geom, maze_params, link_centers, vert_centers)
  File "C:\Blender\2.83\2.83\scripts\addons\mesh_maze-master\mesh_maze.py", line 188, in bevel_extrude
    maze_params['boundary_type'])
  File "C:\Blender\2.83\2.83\scripts\addons\mesh_maze-master\mesh_maze.py", line 227, in get_maze_faces
    path_faces = list({bevel_faces[id] for id in path_face_ids})
  File "C:\Blender\2.83\2.83\scripts\addons\mesh_maze-master\mesh_maze.py", line 227, in <setcomp>
    path_faces = list({bevel_faces[id] for id in path_face_ids})
TypeError: list indices must be integers or slices, not NoneType

**Comment by elfnor** [comment]
Currently, you need to have some or all of the mesh selected, before running the add-on in edit mode. I can only get a similar error as above if there are no vertices selected. Most other operators do nothing if they need a selection to operate and the selection is empty. I'll implement this.

**Comment by elfnor** [comment]
Operator now reports warning if no vertices are selected #59ae3ed
